version: '3.8'

services:
  ocr_app:
    build: .
    container_name: ocr_app_container
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=DistribuidosDB
      - DB_USER=postgres
      - DB_PASSWORD=MySecr3tPassword
    ports:
      - "8000:8000"  # Asegúrate de que el puerto esté mapeado correctamente

  db:
    image: postgres:14.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: DistribuidosDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecr3tPassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
